panel_domain = ""
ptlc_api_key = ""
waiting_server = ""
alias = "easytransfer"

# Nodes
# Node1 = <pterodactyl-node-id>
# Node2 = <pterodactyl-node-id>

# Transfer
# <name>
#   server_id = <pterodactyl-server-id>
#   from = Node1
#   to = Node2
#   allocation_port = 25566
